unique_ids:
  forms:
    StartupForm: 2MW5UAGNT7SAYQI53L3PF23OX4BO46BZ
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: CXQDHQINMC2BTLA5H5KBF5A6LIVCXV4Q
    theme.css: MH5H3S264MTTGUHTYEUTHSZWX3Y5735R
    turnip_token.png: '1695695432470223660599129.50464'
